name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://hpe-cdrm-hcp-vault-cluster-public-vault-3ffbc799.cf52b2ca.z1.hashicorp.cloud:8200
          tlsSkipVerify: true
          namespace: admin
          caCertificate: \${{ secrets.VAULT_CA_CERT }}
          method: token
          token: \${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/secret1 key1
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t vault-action-exampleapp
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t vault-action-exampleapp
